### Obtener todos los clientes  |Listo 
http://localhost:1234/customer/

###Obtener un cliente por su cedula | listo 
http://localhost:1234/customer/27

###Post un nuevo cliente | Listo
POST http://localhost:1234/customer
Content-Type: application/json

{
    "CI": "27",
    "lastName":"Guzman",
    "name":"Juan",
    "email":"juan@gmail.com"
}

###Eliminar un cliente |Listo
DELETE http://localhost:1234/customer/27

###Editar un cliente  |Listo
PATCH http://localhost:1234/customer/25789012
Content-Type: application/json

{
    "CI": "27",
    "lastName":"Guzmannnnnnn"
}

### Obtener todos los empleados | listo
http://localhost:1234/employee/

### Obtener un empleado por su cedula | listo 
http://localhost:1234/employee/27

### empleados que trabajen en cierto establecimiento  | listo 
http://localhost:1234/employee/RIF/J-00112233-4

### agregar un nuevo empleado |listo
POST http://localhost:1234/employee/ 
Content-Type: application/json

{
    "CI": "27",
    "lastName":"Guzmannnnnnn",
    "name":"hola",
    "cellphone":"12345",
    "address":"casa1, calle2",
    "salary":900.00,
    "RIF":"J-00112233-4"
}

###borrar un empledo | listo 
DELETE http://localhost:1234/employee/27

###editar un empleado | listo 
PATCH http://localhost:1234/employee/27
Content-Type: application/json

{
    "address":"tumeremo"
}

### Obtener todos los servicios | listo 
http://localhost:1234/servicie

### Obtener un servicio por su id | Listo 
http://localhost:1234/servicie/1003

### Crear nuevo servicio 
POST http://localhost:1234/servicie
Content-Type: application/json

{
    "nombre_serv":"servicio 1"
}

### Editar un servicio
PATCH http://localhost:1234/servicie/10
Content-Type: application/json

{
    "nombre_ser":"servicio 3"
}

### Obtener todos los establecimientos
http://localhost:1234/establishement/

### Obtener un establecimiento por su RIF
http://localhost:1234/establishement/J-02233-4

### Agregar un nuevo establecimiento
POST http://localhost:1234/establishement/
Content-Type: application/json

{
    "RIF": "J-02233-4",
    "CI_PIC": null,
    "name": "Establecimiento 1",
    "city": "Ciudad 1",
    "date_PIC": "2021-01-01"
}

### Editar un establecimiento
PATCH http://localhost:1234/establishement/
Content-Type: application/json

{
    "RIF": "J-00112233-4",
    "CI_PIC": "1234567890",
    "name": "Establecimiento 1",
    "city": "Ciudad 1",
    "date_PIC": "2021-01-01"
}
### Obtener todos los servicios ofrecidos
http://localhost:1234/offered-services/

### Obtener servicios ofrecidos por RIF de establecimiento
http://localhost:1234/offered-services/rif/J-00112233-4

### Obtener servicios ofrecidos por número de servicio
http://localhost:1234/offered-services/servicio/1

### Obtener un servicio específico por RIF y número de servicio
http://localhost:1234/offered-services/rif/J-00112233-4/servicio/1

### Obtener servicios no ofrecidos
http://localhost:1234/offered-services/no-ofrecidos

### Obtener servicios no ofrecidos por RIF de establecimiento
http://localhost:1234/offered-services/no-ofrecidos/rif/J-00112233-4

### Agregar un nuevo servicio ofrecido
POST http://localhost:1234/offered-services/
Content-Type: application/json

{
    "RIF_establecimiento": "J-00112233-4",
    "nro_servicio": 1
}

### Eliminar un servicio ofrecido
DELETE http://localhost:1234/offered-services/
Content-Type: application/json

{
    "RIF_establecimiento": "J-00112233-4",
    "nro_servicio": 1
}